### ISSUE TITLE
FMEncoderAdd is not defined.

### ISSUE THREAD

**Issue by ZillaRU** [NYXFLOWER/TIP#10]
Hello, Hao Xu! I am working on identifying polypharmacy side effects and need to compare my approach with yours. But, I got a little confused since I could not organize your code to make it work.
Here, `FMEncoderAdd` is not defined. And, is the file `tip-add.py` for training your proposed model TIP-sum?
https://github.com/NYXFLOWER/TIP/blob/c2924d0f1233981e3dd91ecd73f148197318d175/tip-add.py#L162
Any help? 😆Thank you in advance~

**Comment by ZillaRU** [comment]
Thanks for your reply. 😄
I will follow your instruction and try to compare TIP with ours.

**Comment by ZillaRU** [comment]
![image](https://user-images.githubusercontent.com/25343084/137570981-965a73cd-b11d-419e-a938-77ba47ce8b06.png)
The parameter `mod = 'add'` is never used. Is this implementation of `FMEncoder` is identical with your original `FMEncoderAdd`?
Thanks!

**Comment by NYXFLOWER** [comment]
The new TIP implementation has been updated. 

Please find the instruction to reproduce the TIP results here: https://github.com/NYXFLOWER/TIP#Running.

**Comment by NYXFLOWER** [comment]
@all-contributors please add @ZillaRU for bug reports
