### ISSUE TITLE
About drug's CID

### ISSUE THREAD

**Issue by bens1320** [NYXFLOWER/TIP#4]
I recently read your article on Tri-graph Information Propagation for Polypharmacy Side Effect Prediction. I am very interested in this point. I am now confused. What are the CIDs you are constructing for 645 drugs. That is, I don't know what CID corresponds to the serial number between 0-644. I would appreciate it if you could provide it.

**Comment by NYXFLOWER** [comment]
Thank you for your question. You can find the key-map in this file: **"./data/index_map/drug-map.pkl"**. It is stored as a **dictionary** whose **keys** are CIDs and **values** are the index used in the TIP model.
