### ISSUE TITLE
How to solve dependency error? GPU

### ISSUE THREAD

**Issue by Chertoganov** [NYXFLOWER/TIP#7]
ERROR: Could not find a version that satisfies the requirement anaconda-navigator==1.9.7 (from -r requirements_gpu.txt (line 4)) (from versions: none)
ERROR: No matching distribution found for anaconda-navigator==1.9.7 (from -r requirements_gpu.txt (line 4))

P.S. Can you write clear code please without dependency error, please use virtualenv ?

**Comment by shree970** [comment]
You can remove anaconda/conda dependencies. Also installing below packages before installing requirements helped me:

sudo apt install unixodbc-dev
sudo apt-get install libgnutls28-dev
apt install libgmp-dev libmpfr-dev libmpc-dev

**Comment by Chertoganov** [comment]
thanks)

чт, 20 авг. 2020 г. в 09:06, shree970 <notifications@github.com>:

**Comment by NYXFLOWER** [comment]
@all-contributors please add @shree970 and @Chertoganov for bug reports.

**Comment by NYXFLOWER** [comment]
@all-contributors please add @Chertoganov for dug

**Comment by NYXFLOWER** [comment]
@all-contributors please add @Chertoganov for bug reports
